### PR TITLE
Add RNG GUI

### PR DESCRIPTION
**Pull request by NightKoneko**
Added GUI, cleaned up code, etc

You are welcome

### CODE REVIEW

**Comment by Realswitzer** [comment]
```sh
Traceback (most recent call last):
  File "/Users/Swotz/./rpg-gui.py", line 3, in <module>
    import dearpygui.dearpygui as dpg
ModuleNotFoundError: No module named 'dearpygui'
```

**Comment by Realswitzer** [comment]
I assume the module `dearpygui` needs to be installed, should probably add an install script or at least a check (import and if module not found, exit and tell person to install module with pip). Also adding CLI options would be nice, i.e. `./randomnumbergenerator.py -l 1 -h 10` which prints a random number, say `4`. This could greatly increase the efficiency, although replacing -l and -h which something more easy to remember could help with usage.

**Comment by Realswitzer** [comment]
After installing with pip, still won't run. Not sure if its a cross compatibility issue -- due to using Mac --, a Python version issue, or if the package itself is messed up. I highly doubt its pip being out of date as it should install packages all the same.
```sh
switz@swotzterm cwd:~ $ ./rpg-gui.py
Traceback (most recent call last):
  File "/Users/Swotz/./rpg-gui.py", line 3, in <module>
    import dearpygui.dearpygui as dpg
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dearpygui/dearpygui.py", line 22, in <module>
    import dearpygui._dearpygui as internal_dpg
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dearpygui/_dearpygui.so, 2): Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dearpygui/_dearpygui.so
  Reason: image not found
```

**Comment by NightKoneko** [comment]
hmmm that is odd... all you have to install is dearpygui and it should work...

**Comment by NightKoneko** [comment]
> I assume the module `dearpygui` needs to be installed, should probably add an install script or at least a check (import and if module not found, exit and tell person to install module with pip). Also adding CLI options would be nice, i.e. `./randomnumbergenerator.py -l 1 -h 10` which prints a random number, say `4`. This could greatly increase the efficiency, although replacing -l and -h which something more easy to remember could help with usage.

I agree, I just don't really know how to do that lol

**Comment by Realswitzer** [comment]
I'll test it later in a VM since I don't want to deal with dual booting Windows AME and Mac right now - though I should set it up.

**Comment by Realswitzer** [comment]
(i lied, i never actually tested it on windows)

**Comment by NightKoneko** [comment]
:trollface:

**Comment by Realswitzer** [comment]
i can waste anyrun's resources except only gives me 5 minutes to install python and test, and it would be a waste

**Comment by NightKoneko** [comment]
Well I am pretty sure it works, considering I have had some other people try to use it (including one who uses Linux) and it worked for all of them

**Comment by Realswitzer** [comment]
closing for inactivity and ive basically abandoned this lol

**Comment by NightKoneko** [comment]
damn :(

**Comment by Realswitzer** [comment]
the

**Comment by Realswitzer** [comment]
actually i could test windows now. i guess

**Review by Realswitzer — APPROVED** [review]
hi right now im busy merging rest of code with gui, so opts/args work along with gui. should have done yesterday but was playing engi

**Comment by Realswitzer** [comment]
ok i got it merged, not that it works (invalid sender errors and no idea how any of this works).

**Comment by Realswitzer** [comment]
```
PS C:\Users\^_^\github\pysuite> .\randnumgen.py
No arguments! Launching GUI version...because apparently #4 exists
Traceback (most recent call last):
  File "<string>", line 20, in rand_cb
ValueError: invalid sender range2
Traceback (most recent call last):
  File "<string>", line 20, in rand_cb
ValueError: invalid sender range2
Traceback (most recent call last):
  File "<string>", line 20, in rand_cb
ValueError: invalid sender range2
Variable(s) contained non-integers!

PS C:\Users\^_^\github\pysuite>
```
The non-int line is unrelated (something about closing the window i guess), but can't figure out the sender thing. Using `exec(open("rnggui.py").read())` so in theory it would work, as it's not going to have problems with my incompetent implementation. Also not due to file name.

**Comment by NightKoneko** [comment]
wow

**Comment by Realswitzer** [comment]
any ideas? otherwise i guess i can try to remake it in pygame since i dont understand what the problem is. or just not do any gui besides cli because i hate normal people

**Comment by NightKoneko** [comment]
No, I don't have any ideas, sorry. I mean you can try to remake it in pygame if you want lol

**Comment by Realswitzer** [comment]
nah nvm then i hate pygame and all of its userbase, closing unless you fix it.

**Comment by NightKoneko** [comment]
wait what why do you hate pygame, it's pretty nice

**Comment by Realswitzer** [comment]
its pygame.

**Comment by NightKoneko** [comment]
Yeah I guess that's fair, Pygmäe is pretty limited and shit, but still it's not _that_ bad

**Comment by Realswitzer** [comment]
works on windows, not on mac? not sure about penguinOS, ill need to see.
logging onto github and going to reopen PR and maybe merge later (with
fixes so cli perams work)

**Comment by NightKoneko** [comment]
ok

**Pull request closed without merging**
